
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/context.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/scopes.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/container.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/surface.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/component.js"></script>');
;
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/tab.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/subguarded.js"></script>');
;
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/floating.js"></script>');
;
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/nls/i18n.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/toolbar.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/settings.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/ui-plugin.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/ui.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/arena.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/vendor/jquery-ui-autocomplete-html.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/autocomplete.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/dialog.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/utils.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/menuButton.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/button.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/multiSplit.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/port-helper-attribute-field.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/port-helper-multi-split.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/text.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/ui/lib/toggleButton.js"></script>');