
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/contenthandler/lib/wordcontenthandler.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/contenthandler/lib/genericcontenthandler.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/contenthandler/lib/oembedcontenthandler.js"></script>');
;
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/contenthandler/lib/sanitizecontenthandler.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/contenthandler/lib/blockelementcontenthandler.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/contenthandler/lib/contenthandler-plugin.js"></script>');