
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/block/lib/blockmanager.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/block/lib/editormanager.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/block/lib/sidebarattributeeditor.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/block/lib/block.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/block/lib/blockcontenthandler.js"></script>');
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/block/lib/editor.js"></script>');
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
;
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/block/nls/i18n.js"></script>');
;
document.write('<script src="' + ALOHA_BASE_URL + 'plugins/common/block/lib/block-plugin.js"></script>');